plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'com.google.devtools.ksp'
}
// apply plugin: 'kotlin-kapt'
// apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdkVersion 37

    defaultConfig {
        applicationId "com.edxavier.cerberus_sms"
        minSdkVersion 24
        targetSdkVersion 37
        versionCode 1052
        versionName "2026.07.4.2.0"
        vectorDrawables {
            useSupportLibrary true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            resValue "string", "BANNER_FLOTANTE", project.property('ID_BANNER_FLOTANTE')
            resValue "string", "BANNER_PRINCIPAL", project.property('ID_BANNER_PRINCIPAL')
        }
        debug{
            resValue "string", "BANNER_FLOTANTE", project.property('ID_BANNER_PRUEBA')
            resValue "string", "BANNER_PRINCIPAL", project.property('ID_BANNER_PRUEBA')
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
        compose true
        buildConfig true
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    namespace 'com.edxavier.cerberus_sms'
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.2.10"
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.14.0'

    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.8'
    implementation 'androidx.navigation:navigation-ui-ktx:2.9.8'

    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.11.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0'

    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.8'
    implementation 'androidx.navigation:navigation-ui-ktx:2.9.8'

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0"

    implementation "com.github.lisawray.groupie:groupie:2.10.1"
    implementation "com.github.lisawray.groupie:groupie-viewbinding:2.10.1"

    implementation 'androidx.room:room-runtime:2.8.4'
    ksp 'androidx.room:room-compiler:2.8.4'
    implementation 'androidx.room:room-ktx:2.8.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.11.0'

    // ################### COMPOSE ###################
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation 'androidx.compose.material3:material3:1.4.0'
    implementation "androidx.compose.material:material-icons-core:1.7.8"
    implementation "androidx.compose.material:material-icons-extended:1.7.8"
    implementation "androidx.constraintlayout:constraintlayout-compose:1.1.1"
    implementation("io.coil-kt:coil-compose:2.7.0")

    implementation "androidx.navigation:navigation-compose:2.9.8"

    implementation 'androidx.core:core-splashscreen:1.0.1'

    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
    // ################### END COMPOSE ###################


    implementation 'com.opencsv:opencsv:5.12.0'

    implementation("io.coil-kt:coil:2.7.0")

    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-ads:23.6.0'
    // Recommended: Add the Firebase SDK for Google Analytics.
    implementation 'com.google.firebase:firebase-analytics:23.2.0'
    // Add the Firebase SDK for Crashlytics.
    implementation 'com.google.firebase:firebase-crashlytics:20.1.0'

    //ANIMATIONS
    implementation 'com.airbnb.android:lottie:6.7.1'
    // DIALOGS
    implementation 'com.afollestad.material-dialogs:core:3.3.0'
    implementation 'com.afollestad.material-dialogs:input:3.3.0'

    implementation 'androidx.multidex:multidex:2.0.1'

    implementation 'com.pixplicity.easyprefs:EasyPrefs:1.10.0'
    implementation 'com.google.android.gms:play-services-ads:25.4.0'

}
apply plugin: 'com.google.gms.google-services'